name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  bottom_navy_bar: ^6.1.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  rive: ^0.13.13  # Removed flare_flutter
  fl_animated_linechart: ^1.2.0  # Check compatibility or replace
  lottie: ^3.1.2
  simple_animations: ^5.0.2
  flutter_glow: ^0.3.2
  stacked: ^3.4.3
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.0
  # Consider removing flutter_unity_widget or ensure compatibility
  #flutter_unity_widget: ^2022.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
