name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter Packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  bottom_navy_bar: ^6.1.0
  shared_preferences: ^2.1.1
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  rive: ^0.13.13
  simple_animations: ^5.0.2
  flutter_glow: ^0.3.2
  stacked: ^3.4.3
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.0

  # Firebase Integration
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0
  firebase_ml_model_downloader: ^0.3.1

  # UI and Layout
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0+3

  # AI and Machine Learning
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_barcode_scanning: ^0.12.0

  # Data and Visualization Tools
  chart_sparkline: ^1.1.1
  percent_indicator: ^4.2.3
  flutter_html: ^2.2.1

  # Community and Social Engagement
  flutter_contacts: ^1.1.9+2
  share_plus: ^10.0.2
  bottom_sheet_expandable_bar: ^0.1.2

  # Storage and Security
  flutter_secure_storage: ^9.2.2
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/animationFile/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600
